[TEMPERATURE]
TEMP_INPUT_DEVICE = "Dev0"
TEMP_OUTPUT_DEVICE = X

[PRESSURE]
PRESSURE_INPUT_DEVICE = X
PRESSURE_OUTPUT_DEVICE = X


[SIMULATION]
TEMP_SIMULATION = True
TEMP_SIM_DEVICE = COM4
; PICO W is COM4 which is TEMP
PRESSURE_SIMULATION = True
PRESSURE_SIM_DEVICE = COM7
; NON W PICO is COM7 which is PRESSURE